branch-defaults:
  test:
    environment: staging-test
    group_suffix: null
global:
  application_name: ror-app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 3.2 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
